service: hybris-graphql
package:
  individually: true
  exclude:
    - ./**
provider:
  name: openwhisk
  runtime: nodejs:default
  ignore_certs: true
  service: hybris-graphql
plugins:
  - serverless-openwhisk
  - serverless-webpack
resources:
  packages:
    hybris-graphql:
      parameters:
functions:
  dispatcher:
    name: hybris-graphql/dispatcher
    handler: cif/common/dispatcher.main
    concurrency: 200
    annotations:
      web-export: true
    parameters:
      remoteSchemas: # Action with smaller order has "merge priority" in schema conflicts
        product:
          order: 10
          action: hybris-graphql/product
        categoryList:
          order: 20
          action: hybris-graphql/categoryList
        customAttributeMetadata:
          order: 30
          action: hybris-graphql/customAttributeMetadata
        cart:
          order: 40
          action: hybris-graphql/cart
        countries:
          order: 50
          action: hybris-graphql/countries
        customer:
          order: 60
          action: hybris-graphql/customer
        orders:
          order: 70
          action: hybris-graphql/orders

  product:
    name: hybris-graphql/product
    handler: cif/product/src/productResolver.main
    concurrency: 200

  categoryList:
    name: hybris-graphql/categoryList
    handler: cif/category/src/categoryResolver.main
    concurrency: 200

  customAttributeMetadata:
    name: hybris-graphql/customAttributeMetadata
    handler: cif/product/src/customAttributeMetadataResolver.main
    concurrency: 200

  cart:
    name: hybris-graphql/cart
    handler: cif/cart/src/cartResolver.main
    concurrency: 200

  countries:
    name: hybris-graphql/countries
    handler: cif/customer/src/countriesResolver.main
    concurrency: 200

  customer:
    name: hybris-graphql/customer
    handler: cif/customer/src/customerResolver.main
    concurrency: 200

  orders:
    name: hybris-graphql/orders
    handler: cif/order/src/orderResolver.main
    concurrency: 200

  # This deploys a GraphQL introspection endpoint that includes all the Magento types and fields
  # used by the AEM/Magento integration.
  cif-schema:
    name: hybris-graphql/cif-schema
    handler: cif/documentation/introspection.main
    concurrency: 200
    annotations:
      web-export: true