service: hybris-graphql-customer
package:
  individually: true
  exclude:
    - ./**
provider:
  name: openwhisk
  runtime: nodejs:default
  ignore_certs: true
  defaultService: hybris-graphql-customer
  service: ${opt:service, self:provider.defaultService}

custom:
  npm-version: ${file(package.json):name}@${file(package.json):version}
  ow-package: ${opt:ow-package, self:custom.npm-version}

plugins:
  - serverless-openwhisk
  - serverless-webpack

resources:
  packages: ${file(../common/serverlessPackageConfig.js)}

functions:
  dispatcher:
    name: hybris-graphql-customer/dispatcher
    handler: ./dispatcher.main
    concurrency: 200
    annotations:
      web-export: true
    parameters:
      remoteSchemas: # Action with smaller order has "merge priority" in schema conflicts
        countries:
          order: 10
          action: hybris-graphql-customer/countries
        customer:
            order: 20
            action: hybris-graphql-customer/customer
  countries:
    name: hybris-graphql-customer/countries
    handler: src/countriesResolver.main
    concurrency: 200
  customer:
    name: hybris-graphql-customer/customer
    handler: src/customerResolver.main
    concurrency: 200
  