service: hybris-graphql-orders
package:
  individually: true
  exclude:
    - ./**
provider:
  name: openwhisk
  runtime: nodejs:default
  ignore_certs: true
  defaultService: hybris-graphql-orders
  service: ${opt:service, self:provider.defaultService}

custom:
  npm-version: ${file(package.json):name}@${file(package.json):version}
  ow-package: ${opt:ow-package, self:custom.npm-version}

plugins:
  - serverless-openwhisk
  - serverless-webpack

resources:
  packages: ${file(../common/serverlessPackageConfig.js)}

functions:
  dispatcher:
    name: hybris-graphql-orders/dispatcher
    handler: ./dispatcher.main
    concurrency: 200
    annotations:
      web-export: true
    parameters:
      remoteSchemas:
        orders:
          order: 10
          action: hybris-graphql-orders/orders
  orders:
    name: hybris-graphql-orders/orders
    handler: src/orderResolver.main
    concurrency: 200

  