version: 2.1
orbs:
  node: circleci/node@5.0.0
jobs:
  test:
    executor:
      name: node/default
      tag: '10.16.3'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
      - store_test_results:
          path: test/results/unit/results.xml

workflows:
  tests:
    jobs:
      - test
