service: hybris-graphql-cart
package:
  individually: true
  exclude:
    - ./**
provider:
  name: openwhisk
  runtime: nodejs:default
  ignore_certs: true
  defaultService: hybris-graphql-cart
  service: ${opt:service, self:provider.defaultService}

custom:
  npm-version: ${file(package.json):name}@${file(package.json):version}
  ow-package: ${opt:ow-package, self:custom.npm-version}

plugins:
  - serverless-openwhisk
  - serverless-webpack

resources:
  packages: ${file(../common/serverlessPackageConfig.js)}

functions:
  dispatcher:
    name: hybris-graphql-cart/dispatcher
    handler: ./dispatcher.main
    concurrency: 200
    annotations:
      web-export: true
    parameters:
      remoteSchemas: # Action with smaller order has "merge priority" in schema conflicts
        cart:
          order: 10
          action: hybris-graphql-cart/cart
  cart:
    name: hybris-graphql-cart/cart
    handler: src/cartResolver.main
    concurrency: 200

  