service: hybris-graphql-categoryList
package:
  individually: true
  exclude:
    - ./**
provider:
  name: openwhisk
  runtime: nodejs:default
  ignore_certs: true
  defaultService: hybris-graphql-categoryList
  service: ${opt:service, self:provider.defaultService}

custom:
  npm-version: ${file(package.json):name}@${file(package.json):version}
  ow-package: ${opt:ow-package, self:custom.npm-version}

plugins:
  - serverless-openwhisk
  - serverless-webpack

resources:
  packages: ${file(../common/serverlessPackageConfig.js)}

functions:
  dispatcher:
    name: hybris-graphql-categoryList/dispatcher
    handler: ./dispatcher.main
    concurrency: 200
    annotations:
      web-export: true
    parameters:
      remoteSchemas:
        categoryList:
          order: 10
          action: hybris-graphql-categoryList/categoryList
    categoryList:
      name: hybris-graphql-categoryList/categoryList
      handler: src/categoryResolver.main
      concurrency: 200
  